### ISSUE TITLE
 Could not resolve "xlsx" vite js

### ISSUE THREAD

**Issue by RussHide** [securedeveloper/react-data-export#177]
![image](https://user-images.githubusercontent.com/63980905/212785229-aef1adb4-eb18-4a2d-bbb5-1ae8bba1df5f.png)

 node_modules/tempa-xlsx/ods.js:13:29:
      13 │     catch(ee) { return require('xl' + 'sx').utils; }
         │                                ~~~~
         ╵                                "./xlsx"

  Use the relative path "./xlsx" to reference the file "node_modules/tempa-xlsx/xlsx.js". Without
  the leading "./", the path "xlsx" is being interpreted as a package path instead.

6:30:55 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/tempa-xlsx/ods.js:13:29: ERROR: Could not resolve "xlsx"
    at failureErrorWithLog (C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:1566:15)
    at C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:1022:7)
    at C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:726:9)    at Socket.readFromStdout (C:\Users\Yone\Desktop\react-controlasistencia-uadec\node_modules\esbuild\lib\main.js:647:7)

**Comment by AnointingMax** [comment]
Any resolution to this error?
